language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-assemble-node-api' ]; then cd .. && eval "mv $currentfolder generator-assemble-node-api" && cd generator-assemble-node-api; fi

